# Generated by Django 4.0 on 2021-12-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lisences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=200)),
                ('Epicor_version', models.CharField(max_length=50)),
                ('Epicor_type', models.CharField(choices=[('On-premise', 'On-premise'), ('Cloud', 'Cloud')], default='Cloud', max_length=50)),
                ('Activo', models.BooleanField(default=True)),
                ('Fecha_de_registro', models.DateTimeField(verbose_name='Fecha de registro')),
                ('Fecha_de_modificacion', models.DateTimeField(verbose_name='Fecha de modificación')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(default='ACRU', max_length=100)),
                ('Descripcion', models.CharField(max_length=250)),
                ('Fecha_de_registro', models.DateTimeField(verbose_name='Fecha de registro')),
                ('Fecha_de_modificacion', models.DateTimeField(verbose_name='Fecha de modificación')),
            ],
        ),
    ]
