# Generated by Django 4.0 on 2021-12-14 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lisences', '0002_clientes_productos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clientes',
            new_name='Client',
        ),
        migrations.RenameModel(
            old_name='Productos',
            new_name='Product',
        ),
    ]
