# Generated by Django 4.0 on 2021-12-16 18:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lisences', '0004_lisence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='Fecha_de_modificacion',
        ),
        migrations.RemoveField(
            model_name='client',
            name='Fecha_de_registro',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Fecha_de_modificacion',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Fecha_de_registro',
        ),
        migrations.AddField(
            model_name='client',
            name='Actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='client',
            name='Creado',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lisence',
            name='Actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lisence',
            name='Creado',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 16, 18, 1, 29, 213381), verbose_name='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='product',
            name='Actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Creado',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lisence',
            name='Estado',
            field=models.CharField(choices=[('InActiva', 'InActiva'), ('Vigente', 'Vigente'), ('Vencida', 'Vencida')], default='Vigente', max_length=50),
        ),
        migrations.AlterField(
            model_name='lisence',
            name='Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lisences.userprofile'),
        ),
    ]
