# Generated by Django 4.0 on 2021-12-16 18:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lisences', '0006_usuario_alter_lisence_creado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lisence',
            name='Creado',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 16, 18, 31, 56, 190980), verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='lisence',
            name='Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lisences.usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Creado',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 16, 18, 31, 56, 190476), verbose_name='Fecha de creación'),
        ),
    ]
